# prometheus.yml
global:
  scrape_interval: 5s # Busca dados a cada 5 segundos

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'app-votacao'
    static_configs:
      - targets: ['app-votacao:5000']